const COMMON_ACTION_TYPE ="COMMON_ACTION_TYPE"

const ADD_ARTICLE = "ADD_ARTICLE";

const ADD_BOOK = "ADD_BOOK";

const DELETE_ARTICLE = "DELETE_ARTICLE";



export {COMMON_ACTION_TYPE,ADD_ARTICLE,ADD_BOOK,DELETE_ARTICLE};